version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: offered-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PG_USER} -d ${PG_DATABASE}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  server:
    container_name: offered-server
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  
  client:
    container_name: offered-client
    build:
      context: ./client
    ports:
      - "3000:80"
    links:
      - server
    depends_on:
      - server

volumes:
  db:
    driver: local