name: Build and Deploy to Google Compute Engine

on:
  push:
    # Turning off staging for now...
    # branches:
    #   - master
    tags:
      - v\d+\.\d+\.\d+

env:
  PROJECT_ID: offered

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV
        run: |-
          if [ ${GITHUB_REF##*/} = "master" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
          else 
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      # Configure Docker to use the gcloud command-line tool as 
      # a credential helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          make build

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          make push

      - name: Deploy
        run: |-
          make deploy
